############################################################################
# 智爱陪伴 - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_ZHI_AI_PROGNAME)
PRIORITY  = $(CONFIG_ZHI_AI_PRIORITY)
STACKSIZE = $(CONFIG_ZHI_AI_STACKSIZE)
MODULE    = $(CONFIG_LVX_USE_CONTEST2026_233_ZHI_AI)

MAINSRC = zhi_ai_main.c

include $(APPDIR)/Application.mk
