/**
 * 给 host 测试用的假 <nuttx/config.h>
 *
 * 这是给谁用的：hello_app 的 member2 那套 host 单测 —— `run_host_tests.sh` 在 PC 上
 * 直接编 app/hello_app 的四个 .c（ai_state_machine / ai_llm / ai_sound_detect /
 * ai_care）加 tests/test_member2.c，它们经各自的头文件 `#include <nuttx/config.h>`。
 *
 * 真身在哪：真机那份是构建时自动生成的（openvela 这边对应本工程的那一份在
 * cmake_out/contest2026_233_board_sf32lb52_ai/include/nuttx/config.h，头一行写着
 * "Autogenerated! Do not edit."）。PC 上编没有它，本文件只放 host 这条编译路径
 * 真正读到的常量。
 *
 * ⚠️ 这份文件**只在 host 测试的 -I 里**（见 run_host_tests.sh 的 -I$STUBS）；
 *    真机固件编的是 NuttX 生成的那份，两边互不影响。
 *    include guard 用本目录自己的 __HELLO_APP_HOST_STUB_ 前缀（与同目录的 wdog.h /
 *    semaphore.h 一致），不照抄真身的 __INCLUDE_NUTTX_CONFIG_H —— 换个前缀，万一两份
 *    同时出现在包含路径上也不会把真那份顶掉。
 *    以后某个 .c 新读了某个 CONFIG_ 开关/常量，编不过时往这里补一行。
 *
 * OK —— 谁用：ai_state_machine.c / ai_llm.c / ai_sound_detect.c / ai_care.c 里成片的
 *   `return OK;`，以及 tests/test_member2.c 的 `assert(... == OK)`。
 *   真身其实**不在 nuttx/config.h 里** —— NuttX 把它和 ERROR 摆在同一段 enum 里，
 *   位置是 openvela 的 nuttx/include/sys/types.h（`#undef OK` 之后
 *   `enum { ERROR = -1, OK = 0 }`）；真机代码是因为顺手引了 <errno.h> 之类的标准头
 *   才间接拿到它。host 上那些标准头是 glibc 的、没有 OK，而这四个模块在 host 路径上
 *   引到的 NuttX 头只有 <nuttx/config.h>（另两个是 <nuttx/wdog.h>、<nuttx/semaphore.h>，
 *   也都不定义 OK），所以借这份假头把它带上。
 *   取值口径与真身一致：0 = 成功；失败值由被测代码自己返回负 errno（-EINVAL /
 *   -ENOSPC / -ETIMEDOUT 等），不经过本文件。
 *
 * 真身里有、但**故意不在这里定义**的几个开关（前两条是实测过的，不是推测）：
 *   CONFIG_HELLO_APP_LLM_AI_AGENT（真机 =1）—— 定义不了。ai_llm.c 的 #ifdef 分支
 *       会 `#include <velaclaw/client.h>`（真身在 openvela 的
 *       packages/ai_agent/include/velaclaw/client.h），不在 host 的 -I 里，
 *       实测加 -DCONFIG_HELLO_APP_LLM_AI_AGENT 直接
 *       "fatal error: velaclaw/client.h: No such file or directory"。
 *       于是 host 编的是 ai_llm.c 的另一条分支（llm_do_http_request 那条），
 *       sem_init/sem_destroy 与等 ai_agent 回包那整段心跳都不参与编译 ——
 *       test_member2.c 的 LLM 用例只碰 llm_init / llm_build_request_json /
 *       llm_deinit / llm_get_state_name，这几条两个分支里都有，所以 host 上测得到。
 *       真要连真机那条分支一起测，得再给 velaclaw 补一份假头，那不属于本文件。
 *   CONFIG_HELLO_APP_SOUND_EVENT（真机 =1）—— 不能定义。ai_sound_detect.c 尾部那两个
 *       弱桩 sound_event_init / sound_event_feed 正是被
 *       `#ifndef CONFIG_HELLO_APP_SOUND_EVENT` 包着的，而门控线程里
 *       （ai_sound_detect.c:1612）会调 sound_event_feed；host 上没有 sound_event.c，
 *       实测定义它就变成 "undefined reference to `sound_event_feed`"。留空才能链上。
 *   CONFIG_HELLO_APP_PROGNAME / _PRIORITY / _STACKSIZE（真机有）—— 这四个模块一个都
 *       没读，不加。
 *   CONFIG_HELLO_APP_EDGE_IMPULSE 与 CONFIG_DEBUG_AI_*（真机 config.h 里也没有，
 *       已 grep 确认）—— 真机与 host 一致地"未定义"，同样不加。
 *   ERROR（真身与 OK 同处一个 enum，值 -1）—— 这四个模块没有引用（出现的
 *       LLM_STATE_ERROR / DETECT_STATE_ERROR 是枚举名，不是这个宏），按"只补真正被
 *       引用到的"不加；哪天有模块真用了再补一行。
 */

#ifndef __HELLO_APP_HOST_STUB_NUTTX_CONFIG_H
#define __HELLO_APP_HOST_STUB_NUTTX_CONFIG_H

#define OK      0

#endif /* __HELLO_APP_HOST_STUB_NUTTX_CONFIG_H */
